let enKeysObj = {
    AltLeft: { en: 'Alt', order: 56 },
    AltRight: { en: 'Alt', order: 58 },
    ArrowDown: { en: 'ArrowDown', order: 61 },
    ArrowLeft: { en: 'ArrowLeft', order: 60 },
    ArrowRight: { en: 'ArrowRight', order: 62 },
    ArrowUp: { en: 'ArrowUp', order: 53 },
    Backquote: { en: '`', order: 0 },
    Backslash: { en: '\\', order: 27 },
    Backspace: { en: 'Backspace', order: 13 },
    BracketLeft: { en: '[', order: 25 },
    BracketRight: { en: ']', order: 26 },
    CapsLock: { en: 'CapsLock', order: 30 },
    Comma: { en: ',', order: 50 },
    ControlLeft: { en: 'Control', order: 55 },
    ControlRight: { en: 'Control', order: 59 },
    Delete: { en: 'Delete', order: 28 },
    Digit0: { en: '0', order: 10 },
    Digit1: { en: '1', order: 1 },
    Digit2: { en: '2', order: 2 },
    Digit3: { en: '3', order: 3 },
    Digit4: { en: '4', order: 4 },
    Digit5: { en: '5', order: 5 },
    Digit6: { en: '6', order: 6 },
    Digit7: { en: '7', order: 7 },
    Digit8: { en: '8', order: 8 },
    Digit9: { en: '9', order: 9 },
    Enter: { en: 'Enter', order: 41 },
    Equal: { en: '=', order: 12 },
    KeyA: { en: 'a', order: 30 },
    KeyB: { en: 'b', order: 47 },
    KeyC: { en: 'c', order: 45 },
    KeyD: { en: 'd', order: 32 },
    KeyE: { en: 'e', order: 17 },
    KeyF: { en: 'f', order: 33 },
    KeyG: { en: 'g', order: 34 },
    KeyH: { en: 'h', order: 35 },
    KeyI: { en: 'i', order: 22 },
    KeyJ: { en: 'j', order: 36 },
    KeyK: { en: 'k', order: 37 },
    KeyL: { en: 'l', order: 38 },
    KeyM: { en: 'm', order: 49 },
    KeyN: { en: 'n', order: 48 },
    KeyO: { en: 'o', order: 23 },
    KeyP: { en: 'p', order: 24 },
    KeyQ: { en: 'q', order: 15 },
    KeyR: { en: 'r', order: 18 },
    KeyS: { en: 's', order: 31 },
    KeyT: { en: 't', order: 19 },
    KeyU: { en: 'u', order: 21 },
    KeyV: { en: 'v', order: 46 },
    KeyW: { en: 'w', order: 16 },
    KeyX: { en: 'x', order: 44 },
    KeyY: { en: 'y', order: 20 },
    KeyZ: { en: 'z', order: 43 },
    Minus: { en: '-', order: 11 },
    Period: { en: '.', order: 51 },
    Quote: { en: "'", order: 40 },
    Semicolon: { en: ';', order: 39 },
    ShiftLeft: { en: 'Shift', order: 42 },
    ShiftRight: { en: 'Shift', order: 54 },
    Slash: { en: '/', order: 52 },
    Space: { en: '', order: 57 },
    Tab: { en: 'Tab', order: 14 },
};

let rohstoffe = {
    AltLeft: { en: 'Alt', order: 56, ru: 'Alt' },
    AltRight: { en: 'Alt', order: 58, ru: 'AltGraph' },
    ArrowDown: { en: 'ArrowDown', order: 61, ru: 'ArrowDown' },
    ArrowLeft: { en: 'ArrowLeft', order: 60, ru: 'ArrowLeft' },
    ArrowRight: { en: 'ArrowRight', order: 62, ru: 'ArrowRight' },
    ArrowUp: { en: 'ArrowUp', order: 53, ru: 'ArrowUp' },
    Backquote: { en: '`', order: 0, ru: 'ё' },
    Backslash: { en: '\\', order: 27, ru: '\\' },
    Backspace: { en: 'Backspace', order: 13, ru: 'Backspace' },
    BracketLeft: { en: '[', order: 25, ru: 'х' },
    BracketRight: { en: ']', order: 26, ru: 'ъ' },
    CapsLock: { en: 'CapsLock', order: 30, ru: 'CapsLock' },
    Comma: { en: ',', order: 50, ru: 'б' },
    ControlLeft: { en: 'Control', order: 55, ru: 'Control' },
    ControlRight: { en: 'Control', order: 59, ru: 'Control' },
    Delete: { en: 'Delete', order: 28, ru: 'Delete' },
    Digit0: { en: '0', order: 10, ru: '0' },
    Digit1: { en: '1', order: 1, ru: '1' },
    Digit2: { en: '2', order: 2, ru: '2' },
    Digit3: { en: '3', order: 3, ru: '3' },
    Digit4: { en: '4', order: 4, ru: '4' },
    Digit5: { en: '5', order: 5, ru: '5' },
    Digit6: { en: '6', order: 6, ru: '6' },
    Digit7: { en: '7', order: 7, ru: '7' },
    Digit8: { en: '8', order: 8, ru: '8' },
    Digit9: { en: '9', order: 9, ru: '9' },
    Enter: { en: 'Enter', order: 41, ru: 'Enter' },
    Equal: { en: '=', order: 12, ru: '=' },
    KeyA: { en: 'a', order: 30, ru: 'ф' },
    KeyB: { en: 'b', order: 47, ru: 'и' },
    KeyC: { en: 'c', order: 45, ru: 'с' },
    KeyD: { en: 'd', order: 32, ru: 'в' },
    KeyE: { en: 'e', order: 17, ru: 'у' },
    KeyF: { en: 'f', order: 33, ru: 'а' },
    KeyG: { en: 'g', order: 34, ru: 'п' },
    KeyH: { en: 'h', order: 35, ru: 'р' },
    KeyI: { en: 'i', order: 22, ru: 'ш' },
    KeyJ: { en: 'j', order: 36, ru: 'о' },
    KeyK: { en: 'k', order: 37, ru: 'л' },
    KeyL: { en: 'l', order: 38, ru: 'д' },
    KeyM: { en: 'm', order: 49, ru: 'ь' },
    KeyN: { en: 'n', order: 48, ru: 'т' },
    KeyO: { en: 'o', order: 23, ru: 'щ' },
    KeyP: { en: 'p', order: 24, ru: 'з' },
    KeyQ: { en: 'q', order: 15, ru: 'й' },
    KeyR: { en: 'r', order: 18, ru: 'к' },
    KeyS: { en: 's', order: 31, ru: 'ы' },
    KeyT: { en: 't', order: 19, ru: 'е' },
    KeyU: { en: 'u', order: 21, ru: 'г' },
    KeyV: { en: 'v', order: 46, ru: 'м' },
    KeyW: { en: 'w', order: 16, ru: 'ц' },
    KeyX: { en: 'x', order: 44, ru: 'ч' },
    KeyY: { en: 'y', order: 20, ru: 'н' },
    KeyZ: { en: 'z', order: 43, ru: 'я' },
    Minus: { en: '-', order: 11, ru: '-' },
    Period: { en: '.', order: 51, ru: 'ю' },
    Quote: { en: "'", order: 40, ru: 'э' },
    Semicolon: { en: ';', order: 39, ru: 'ж' },
    ShiftLeft: { en: 'Shift', order: 42, ru: 'Shift' },
    ShiftRight: { en: 'Shift', order: 54, ru: 'Shift' },
    Slash: { en: '/', order: 52, ru: '.' },
    Space: { en: '', order: 57, ru: ' ' },
    Tab: { en: 'Tab', order: 14, ru: 'Tab' },
}